Add Level Properties
hameerabbasi/xsparse pull request #11
Opened 2022-07-18 09:21 UTC by bharath2438

I've added the `container_traits` for `vector`, `set` & `unordered_map`. If the template parameters look good, we can get the levels to inherit from these container traits.

2022-07-19 07:07 UTC, hameerabbasi requested changes
`Containers` will be replaced everywhere with an instantiation of `container_traits`.

2022-07-19 07:12 UTC, hameerabbasi commented
We should also stick to a naming scheme, please use `Vec`, `Set` and `Map` as it matches with `IK`, etc.

2022-07-19 08:14 UTC, hameerabbasi commented
No need to inherit, but replace `Containers` with one type instead of a pack and pass an instance of `container_traits` by default.

2022-07-19 08:26 UTC, hameerabbasi requested changes

2022-07-19 08:26 UTC, hameerabbasi commented on include/xsparse/util/container_traits.hpp
> +    struct container_traits;
No need for this variant.

2022-07-20 14:16 UTC, bharath2438 commented
@hameerabbasi inside `container_traits`, do I set the container-type, say `TVec` to `std::vector<uintptr_t>`. If not, what should I replace uintptr_t with?

2022-07-20 14:44 UTC, hameerabbasi commented
> inside `container_traits`, do I set the container-type, say `TVec` to `std::vector<uintptr_t>`. If not, what should I replace uintptr_t with?

Use `template <TVec<typename>, TSet<typename>, TMap<typename, typename>>`, then use `container_traits<...>::vector<IK>`.

2022-07-20 17:13 UTC, hameerabbasi commented
> template <TVec<typename>, TSet<typename>, TMap<typename, typename>>

That is a way of saying we aren't taking types, but generics in the template. Like `std::vector` (a generic) instead of `std::vector<uintptr_t>` (a type).

2022-07-21 07:03 UTC, bharath2438 commented
@hameerabbasi Is the latest commit close to what we want in `container_traits`? Or instead of taking `IK` and `PK`, we can specify them in the levels?

2022-07-21 18:23 UTC, hameerabbasi commented
We should specify them in the levels, not here.

2022-07-22 13:48 UTC, hameerabbasi commented
> Okay, so we are taking a generic like std::vector as the template parameter, but inside container_traits, we need a type for Vec, so we'll have something like using Vec = TVec<[type]>, how do I get [type]?

You don't. You specify the generic itself: `using Vec = TVec;`, and use it as: `container_traits<...>::Vec<[type]>`

Think of it as specifying a function pointer versus an argument to a function.

2022-07-22 14:32 UTC, bharath2438 commented
> You don't. You specify the generic itself: `using Vec = TVec;` 
This line is throwing error C3205. It says that the argument list for template template parameter is missing.

2022-07-22 15:15 UTC, hameerabbasi commented
Hmm, we'll have to find out how it's spelled, but it's the right API at least.

2022-07-24 12:21 UTC, bharath2438 commented
@hameerabbasi I've just changed the `compressed` level container types. If it looks okay, I will make the changes for all levels and in the tests too.

2022-07-24 13:35 UTC, hameerabbasi commented
Looks okay, some syntactic errors but I hope you'll be able to figure those out. 😉

2022-07-25 11:20 UTC, hameerabbasi commented
Hint: You have an extra `template` in some places. It never shows up after `::`.

2022-07-25 11:26 UTC, bharath2438 commented
> Hint: You have an extra `template` in some places. It never shows up after `::`.
But it compiles on my windows machine only if the `template` is specified. Is it because of MSVC?

2022-07-25 16:19 UTC, bharath2438 commented
> Add it before `ContainerTraits`.

Actually, I tried this, but it does not compile. I checked [this](https://stackoverflow.com/questions/610245/where-and-why-do-i-have-to-put-the-template-and-typename-keywords) thread according to which specifying `template` for dependent templates is necessary. I guess adding `typename` wherever we are using types should get CI passing.

2022-07-25 16:26 UTC, hameerabbasi commented
That sounds about right!

2022-07-25 17:04 UTC, hameerabbasi approved these changes
I think we're still missing a way to discover if a particular container is sorted or unsorted, but that can be done in another PR.

2022-07-25 17:05 UTC, merged